const helloStickersId = [
  "CAACAgIAAxkBAAIFWWKM_22ZdaUodQVbP47Esz5mrg12AAJUFgAC0HtBSfy5WNnzRlYoJAQ",
  "CAACAgIAAxkBAAIFX2KNAAG8v6BWwImGxSZeMO-z5B6nowAChxUAAj0PUEnem2b91sejvyQE",
  "CAACAgIAAxkBAAIFYGKNAAHaywRoCvOsV7vb6C_sW7pK9wAC-xUAAgLfUUlAKQs-3ZtHgSQE",
  "CAACAgIAAxkBAAIFYWKNAAH_Vj2HK9-QwpoLmKGYk_OPlgACGxMAAifBcUnRvYBFTxWL5SQE",
  "CAACAgIAAxkBAAIFYmKNAZC8zpD76q0LweXlyLExDNaHAALLDQACNH-gSJZHaNxgmuSmJAQ",
  "CAACAgIAAxkBAAIFY2KNAfGIWJ5COk-XVOGbn5An7_NsAAIYDgAChNsQSmWvpOQLcyFTJAQ",
  "CAACAgIAAxkBAAIFZGKNAkC3u5AxF3KGyuB3Z831zsNTAALyDgACILd4SgVaZWmYPAwyJAQ",
  "CAACAgIAAxkBAAIFZGKNAkC3u5AxF3KGyuB3Z831zsNTAALyDgACILd4SgVaZWmYPAwyJAQ",
  "CAACAgIAAxkBAAIFZmKNAws3mk4JFDxZfWRlcvf1253mAAKREgACuSQAAUr_HK7bOYfO8yQE",
  "CAACAgIAAxkBAAIFZ2KNAyWqpym_wj2wo1z1cgU20oKEAAKjCgAC_564SH9OyX2bl68TJAQ",
];

export default helloStickersId;
